### ISSUE TITLE
How can I build and install this?

### ISSUE THREAD

**Issue by PhilAndrew** [cb372/intellij-idris#1]

**Comment by Dessix** [comment]
I'd love to do the same- this language is awesome, and a familiar IDE would bring it into scope. I'll see what I can do to assist and contribute.

**Comment by PhilAndrew** [comment]
Just for interest, I build my Idris code using SBT inside my build here: https://github.com/PhilAndrew/JumpMicro/blob/master/JMScalaJs/build.sbt

**Comment by cb372** [comment]
I'm afraid the plugin a long way away from being useful. I spent about an hour on it, tweeted some screenshots, then got distracted by buying a house, so I haven't had much time to spend on it.

I'll at least add a README describing how I set things up so I can run the plugin using a run configuration in IntelliJ. The process for doing so is a bit lame and manual at the moment.

I'll also make some notes about what I've done so far and my vague implementation plan.

**Comment by cb372** [comment]
I've added a README and some implementation notes.

**Comment by PhilAndrew** [comment]
Don't get distracted by silly things like buying a house, buy a cat and get distracted by that.

**Comment by PhilAndrew** [comment]
I just tried tonight to build and debug following your instructions, note that I don't use the community edition, however I get the following error. Any immediate idea why? I'll investigate further tomorrow.

"C:\Program Files\Java\jdk1.8.0_112\bin\java" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:49276,suspend=y,server=n -Xmx512m -Xms256m -XX:MaxPermSize=250m -ea "-Xbootclasspath/a:C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\boot.jar" -Didea.config.path=C:\Users\philip\.IntelliJIdea2016.3\system\plugins-sandbox\config -Didea.system.path=C:\Users\philip\.IntelliJIdea2016.3\system\plugins-sandbox\system -Didea.plugins.path=C:\Users\philip\.IntelliJIdea2016.3\system\plugins-sandbox\plugins -Didea.classpath.index.enabled=false -Didea.required.plugins.id=cb372.intellij.idris -javaagent:C:\Users\philip\.IntelliJIdea2016.3\system\groovyHotSwap\gragent.jar -Dfile.encoding=windows-1252 -classpath "C:\Program Files\Java\jdk1.8.0_112\lib\tools.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\log4j.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\jdom.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\trove4j.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\openapi.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\util.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\extensions.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\bootstrap.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\idea_rt.jar;C:/Program Files (x86)/JetBrains/IntelliJ IDEA 2016.3.2\lib\idea.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.2\lib\idea_rt.jar" com.intellij.idea.Main
Connected to the target VM, address: '127.0.0.1:49276', transport: 'socket'
java.lang.Throwable: Extension class cb372.intellij.idris.IdrisFileTypeFactory does not implement class com.intellij.openapi.fileTypes.FileTypeFactory. It came from ExtensionComponentAdapter[cb372.intellij.idris.IdrisFileTypeFactory]: plugin=PluginDescriptor[name='Idris', classpath='C:\Users\philip\.IntelliJIdea2016.3\system\plugins-sandbox\plugins\intellij-idris']
	at com.intellij.openapi.extensions.Extensions$SimpleLogProvider.error(Extensions.java:218)
	at com.intellij.openapi.extensions.impl.ExtensionsAreaImpl.error(ExtensionsAreaImpl.java:422)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:261)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:191)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:102)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:89)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:49)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:310)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:272)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
	at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
	at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:68)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by PhilAndrew** [comment]
I tried with community edition Version 2017.1 EAP (171.3224.1) and it failed with the same error.

**Comment by PhilAndrew** [comment]
Im on Windows
